#!/usr/bin/env python3
"""
Automated TODO List Manager for Docker Homelab Manager
Tracks tasks, analyzes codebase, and maintains project status
"""

import os
import json
import re
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Set
import anthropic

class TodoManager:
    """Automated TODO list management system"""

    def __init__(self, api_key: str = None):
        self.project_root = Path(__file__).parent.parent
        self.todo_file = self.project_root / "TODO.md"
        self.api_key = api_key or os.environ.get("ANTHROPIC_API_KEY")
        self.client = anthropic.Anthropic(api_key=self.api_key) if self.api_key else None

    def scan_codebase_todos(self) -> List[Dict]:
        """Scan all source files for TODO comments"""
        todos = []

        # Scan C++ files
        for ext in ['*.cpp', '*.h']:
            for file_path in self.project_root.rglob(ext):
                if 'build' in str(file_path) or '.git' in str(file_path):
                    continue

                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    lines = f.readlines()
                    for line_num, line in enumerate(lines, 1):
                        # Match TODO comments
                        match = re.search(r'//\s*TODO:?\s*(.+)', line, re.IGNORECASE)
                        if match:
                            todos.append({
                                'file': str(file_path.relative_to(self.project_root)),
                                'line': line_num,
                                'text': match.group(1).strip(),
                                'context': line.strip()
                            })

        return todos

    def categorize_todos(self, todos: List[Dict]) -> Dict[str, List[Dict]]:
        """Categorize TODOs by component/area"""
        categories = {
            'Docker Client': [],
            'Port Scanner': [],
            'Update System': [],
            'Network Diagnostics': [],
            'Error Diagnostics': [],
            'Database': [],
            'GUI': [],
            'Other': []
        }

        for todo in todos:
            file_path = todo['file'].lower()

            if 'dockerclient' in file_path:
                categories['Docker Client'].append(todo)
            elif 'portscanner' in file_path:
                categories['Port Scanner'].append(todo)
            elif 'update' in file_path:
                categories['Update System'].append(todo)
            elif 'networkdiagnostics' in file_path:
                categories['Network Diagnostics'].append(todo)
            elif 'errordiagnostics' in file_path:
                categories['Error Diagnostics'].append(todo)
            elif 'database' in file_path:
                categories['Database'].append(todo)
            elif 'mainwindow' in file_path or 'ui' in file_path:
                categories['GUI'].append(todo)
            else:
                categories['Other'].append(todo)

        return categories

    def generate_todo_markdown(self, categorized_todos: Dict[str, List[Dict]]) -> str:
        """Generate formatted TODO.md content"""
        content = []
        content.append("# Docker Homelab Manager - TODO List")
        content.append(f"\n*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
        content.append("*This file is automatically generated from code TODOs*\n")

        # Summary
        total_todos = sum(len(todos) for todos in categorized_todos.values())
        content.append(f"## Summary\n")
        content.append(f"**Total TODOs**: {total_todos}\n")

        # Category breakdown
        content.append("### By Component\n")
        for category, todos in categorized_todos.items():
            if todos:
                content.append(f"- **{category}**: {len(todos)} tasks")
        content.append("")

        # Priority estimation (if AI available)
        if self.client:
            content.append("## AI-Recommended Priority Order\n")
            priority_order = self.get_priority_order(categorized_todos)
            for i, item in enumerate(priority_order[:10], 1):
                content.append(f"{i}. **{item['task']}** - {item['rationale']}")
            content.append("")

        # Detailed breakdown
        content.append("## Detailed Task List\n")
        for category, todos in categorized_todos.items():
            if not todos:
                continue

            content.append(f"### {category} ({len(todos)} tasks)\n")
            for todo in todos:
                content.append(f"- [ ] {todo['text']}")
                content.append(f"  - **File**: `{todo['file']}:{todo['line']}`")
                content.append(f"  - **Context**: `{todo['context'][:80]}...`")
                content.append("")

        # Implementation phases
        content.append("## Suggested Implementation Phases\n")
        content.append(self.generate_implementation_phases(categorized_todos))

        return "\n".join(content)

    def get_priority_order(self, categorized_todos: Dict[str, List[Dict]]) -> List[Dict]:
        """Use AI to determine priority order of tasks"""
        if not self.client:
            return []

        todo_summary = []
        for category, todos in categorized_todos.items():
            if todos:
                todo_summary.append(f"{category}: {len(todos)} tasks")
                for todo in todos[:3]:  # First 3 from each category
                    todo_summary.append(f"  - {todo['text']}")

        prompt = f"""Analyze these TODO tasks from a C++ Docker management application and recommend the top 10 priority order for implementation:

{chr(10).join(todo_summary)}

Consider:
1. Dependencies (foundational features first)
2. User impact (high-value features)
3. Implementation difficulty
4. Risk (critical functionality)

Respond with JSON array:
[
  {{"task": "Brief task name", "rationale": "Why this is important"}},
  ...
]"""

        try:
            message = self.client.messages.create(
                model="claude-sonnet-4-5-20250929",
                max_tokens=2000,
                messages=[{"role": "user", "content": prompt}]
            )

            response_text = message.content[0].text
            json_start = response_text.find('[')
            json_end = response_text.rfind(']') + 1
            if json_start >= 0:
                return json.loads(response_text[json_start:json_end])
        except Exception as e:
            print(f"AI priority analysis failed: {e}")

        return []

    def generate_implementation_phases(self, categorized_todos: Dict[str, List[Dict]]) -> str:
        """Generate suggested implementation phases"""
        phases = []

        # Phase 1: Foundation
        phase1_count = len(categorized_todos.get('Docker Client', [])) + \
                       len(categorized_todos.get('Database', []))
        if phase1_count > 0:
            phases.append(f"### Phase 1: Foundation ({phase1_count} tasks)")
            phases.append("Focus: Docker Client API integration and Database layer")
            phases.append("- Implement core Docker API calls")
            phases.append("- Set up SQLite database schema")
            phases.append("- Basic container CRUD operations\n")

        # Phase 2: Core Features
        phase2_count = len(categorized_todos.get('Port Scanner', [])) + \
                       len(categorized_todos.get('Update System', []))
        if phase2_count > 0:
            phases.append(f"### Phase 2: Core Features ({phase2_count} tasks)")
            phases.append("Focus: Port scanning and update system")
            phases.append("- Port conflict detection")
            phases.append("- Image update checking")
            phases.append("- Safe update mechanism\n")

        # Phase 3: Advanced Features
        phase3_count = len(categorized_todos.get('Network Diagnostics', [])) + \
                       len(categorized_todos.get('Error Diagnostics', []))
        if phase3_count > 0:
            phases.append(f"### Phase 3: Advanced Features ({phase3_count} tasks)")
            phases.append("Focus: Diagnostics and error handling")
            phases.append("- Network connectivity testing")
            phases.append("- Automated error detection")
            phases.append("- Auto-fix capabilities\n")

        # Phase 4: UI/UX
        phase4_count = len(categorized_todos.get('GUI', []))
        if phase4_count > 0:
            phases.append(f"### Phase 4: User Interface ({phase4_count} tasks)")
            phases.append("Focus: GUI completion and polish")
            phases.append("- Complete all tab implementations")
            phases.append("- Add real-time updates")
            phases.append("- Polish user experience\n")

        return "\n".join(phases)

    def update_todo_file(self):
        """Scan codebase and update TODO.md"""
        print("Scanning codebase for TODOs...")
        todos = self.scan_codebase_todos()
        print(f"Found {len(todos)} TODO items")

        print("Categorizing tasks...")
        categorized = self.categorize_todos(todos)

        print("Generating TODO.md...")
        content = self.generate_todo_markdown(categorized)

        self.todo_file.write_text(content)
        print(f"✓ TODO.md updated: {self.todo_file}")

        return categorized

    def get_completion_stats(self) -> Dict:
        """Calculate project completion statistics"""
        todos = self.scan_codebase_todos()

        # Count implemented vs TODO lines
        total_lines = 0
        todo_lines = len(todos)

        for ext in ['*.cpp', '*.h']:
            for file_path in self.project_root.rglob(ext):
                if 'build' not in str(file_path):
                    try:
                        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                            total_lines += len(f.readlines())
                    except:
                        pass

        return {
            'total_lines': total_lines,
            'todo_count': todo_lines,
            'estimated_completion': max(0, 100 - (todo_lines / total_lines * 100)) if total_lines > 0 else 0
        }

def main():
    """Main entry point"""
    import argparse

    parser = argparse.ArgumentParser(description="TODO List Manager")
    parser.add_argument("--update", action="store_true",
                       help="Update TODO.md from codebase")
    parser.add_argument("--stats", action="store_true",
                       help="Show completion statistics")

    args = parser.parse_args()

    manager = TodoManager()

    if args.stats:
        stats = manager.get_completion_stats()
        print("\n=== Project Statistics ===")
        print(f"Total lines: {stats['total_lines']}")
        print(f"TODO count: {stats['todo_count']}")
        print(f"Estimated completion: {stats['estimated_completion']:.1f}%\n")

    if args.update or not any(vars(args).values()):
        manager.update_todo_file()

if __name__ == "__main__":
    main()
